#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
${HOME}/.fehbg
picom &

#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
bspc monitor -d 一 二 三 四 五

bspc config border_width         2
bspc config window_gap           4
bspc config split_ratio          0.50
bspc config normal_border_color "#4C566A"
bspc config focused_border_color "#5E81AC"
(Cores.)

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding 24

